[package]
name = "idk_uwu_ig"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
lz4_flex = "0.11.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
libc = "0.2"
rkyv = { version = "0.7", features = ["validation", "strict"] }
