title: "Satori Docs"
description: "Documentation for Satori Storage"
theme: "just-the-docs"

url: https://satori-docs.pages.dev
baseurl: ""

logo: "/assets/O5kile01.svg"
favicon_ico: "/assets/favicon.ico"

heading_anchors: true
color_scheme: dark
footer_content: false

custom_css:
  - /assets/css/custom.css

aux_links:
  "GitHub": https://github.com/satoridb/satori

# Exclude WIP files from the site
exclude:
  - clustering.md
  - configurations.md
  - distributed coordination.md
  - quorum writes.md
  - "*.tmp"
  - Gemfile
  - Gemfile.lock
  - LICENSE

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
